### ISSUE TITLE
[问题] 纹理图片无法加载

### ISSUE THREAD

**Issue by zsr-lukezhang** [lingbopro/lingbos-sussy-mod#3]
Wiki中`凌玻块`的纹理图片无法加载。
这应该不是网络问题。
因为下载图片之后“照片”应用提示：
![image](https://github.com/user-attachments/assets/e5d46816-ea5c-479d-ab92-18e85e27b312)
> 似乎不支持此文件格式
`不喜欢`、`点赞`和`硬币`的纹理图片也无法加载。

**Comment by Minemetero** [comment]
此问题不存在

**Comment by Minemetero** [comment]
Hum?

**Comment by Minemetero** [comment]
@lingbopro 给我给权限 :)

**Comment by Minemetero** [comment]
我看看wiki的图片是怎么回事

**Comment by Minemetero** [comment]
![image_2024-08-10_112749365](https://github.com/user-attachments/assets/4e8aba84-e962-4eb4-93a9-bf762837b5c6)
你这问题确实有点大

**Comment by Minemetero** [comment]
可不可以把图片发到这里我下载下来

**Comment by lingbopro** [comment]
> ![image_2024-08-10_112749365](https://github.com/user-attachments/assets/4e8aba84-e962-4eb4-93a9-bf762837b5c6)
> 你这问题确实有点大

？本地十分正常啊

**Comment by zsr-lukezhang** [comment]
可以尝试重新上传

**Comment by lingbopro** [comment]
不对劲啊

**Comment by lingbopro** [comment]
我怀疑是我push的时候git没给我push全

**Comment by zsr-lukezhang** [comment]
那就重新上传啊

**Comment by lingbopro** [comment]
这个东西我本地编译出来的是正常的

**Comment by lingbopro** [comment]
我去看看jar里的纹理正不正常

**Comment by lingbopro** [comment]
![Screenshot_20240810_110430_bin.mt.plus.jpg](https://github.com/user-attachments/assets/a4ed8d8d-7b27-4596-9787-9c68174c3ef3)

jar里的纹理是正常的

**Comment by lingbopro** [comment]
> 那就重新上传啊

我电脑还没开，等一下我去电脑上确认一下

**Comment by lingbopro** [comment]
大概就是因为没传完

我push的时候一直push不上去，挂加速器和挂梯子都不行，中间有一次push到一半了然后连接断了…

当时我直接写了个while循环来push（

**Comment by zsr-lukezhang** [comment]
GitHub Desktop的速度应该可以啊

**Comment by lingbopro** [comment]
> GitHub Desktop的速度应该可以啊

我直接用的git

**Comment by lingbopro** [comment]
我之前挂Steam++一直可以的，但是这回就不行

**Comment by lingbopro** [comment]
那我本地force push一下？

**Comment by zsr-lukezhang** [comment]
> 我之前挂Steam++一直可以的，但是这回就不行

以后代理可以试试Cloudflare Pages 静态资产 代理

**Comment by lingbopro** [comment]
![image](https://github.com/user-attachments/assets/e78f360d-ba27-4d0b-a0c9-8115cb065617)

我本地的没问题
（刚开电脑

**Comment by lingbopro** [comment]
![image](https://github.com/user-attachments/assets/10e4611d-1c0f-43a2-9b43-97475d489507)

force push依然不行

**Comment by lingbopro** [comment]
![image](https://github.com/user-attachments/assets/4ea63bf3-e22f-4dcb-886b-998193db83ca)

这两张图的MD5都不一样
（左边为本地的）

**Comment by zsr-lukezhang** [comment]
传输过程中损坏了

**Comment by lingbopro** [comment]
> 传输过程中损坏了

应该是的
但是问题在于我本地force push的时候git告诉我Everything up-to-date，导致并不会push上去

**Comment by lingbopro** [comment]
![image](https://github.com/user-attachments/assets/4015d32e-434d-41e1-ad14-9d989dc6b584)

emmm

**Comment by lingbopro** [comment]
或者我可以在github.dev提交一下试试

**Comment by lingbopro** [comment]
github.dev上提交成功了

**Comment by lingbopro** [comment]
我还要去更新一下tag

**Comment by zsr-lukezhang** [comment]
Connection was reset是不是换节点了

> ![image](https://private-user-images.githubusercontent.com/148617407/356788015-4015d32e-434d-41e1-ad14-9d989dc6b584.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjM5NDUsIm5iZiI6MTcyMzI2MzY0NSwicGF0aCI6Ii8xNDg2MTc0MDcvMzU2Nzg4MDE1LTQwMTVkMzJlLTQzNGQtNDFlMS1hZDE0LTlkOTg5ZGM2YjU4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMFQwNDIwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWM0Mjc2YzU4ODIyNWViMDNjNTJlNzFiMDYzNWVlMDU2Mjk3MjE4Y2IxZmUwMTJlNmJiZDlhN2FmODVkYTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IDnVm8AB23agVCbaXhh1NMK_ocTVUWa_huZsYaWO9aw)
> 
> emmm

**Comment by lingbopro** [comment]
现在可以关了

**Comment by lingbopro** [comment]
我真就，modrinth因为我没英文描述不给我过审

![image](https://github.com/user-attachments/assets/bd545107-1d64-490d-acfa-f699cf6dfaab)
